title: Anggoletomi Marlis Putra # your name (or website title) here
logo: "/images/logo-avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my GitHub Page!
  <br><br>
  I post my data related project here.
  <br>
  <img src="https://esdm.jatengprov.go.id/images/OPENDATASOFT_MONITORING.gif" width="100px">
  
  <style>
    .social {
      width:50%;
      height:auto;
      margin:auto;
    }
  </style>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#0077B5;" onclick="window.open('https://www.linkedin.com/in/anggoletomi/', '_blank').focus();">
    <img src="https://img.shields.io/badge/linkedin-0077B5?style=for-the-badge&logo=linkedin&logoColor=white&link=https://www.linkedin.com/in/anggoletomi/" alt="LinkedIn">
  </div>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#121011;" onclick="window.open('https://github.com/anggoletomi/', '_blank').focus();">
    <img src="https://img.shields.io/badge/github-121011?style=for-the-badge&logo=github&logoColor=white&link=https://github.com/anggoletomi/" alt="GitHub">
  </div>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#20BEFF;" onclick="window.open('https://www.kaggle.com/anggoletomi', '_blank').focus();">
    <img src="https://img.shields.io/badge/kaggle-20BEFF?style=for-the-badge&logo=kaggle&logoColor=white&link=https://www.kaggle.com/anggoletomi" alt="Kaggle">
  </div>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#E97627;" onclick="window.open('https://public.tableau.com/app/profile/anggoletomi.marlis.putra', '_blank').focus();">
    <img src="https://img.shields.io/badge/tableau-E97627?style=for-the-badge&logo=Tableau&logoColor=white&link=https://public.tableau.com/app/profile/anggoletomi.marlis.putra" alt="Tableau">
  </div>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#617C58;" onclick="window.open('https://www.datacamp.com/profile/anggoletomiputra', '_blank').focus();">
    <img src="https://img.shields.io/badge/-Datacamp-617C58?style=for-the-badge&logo=datacamp&logoColor=white&link=https://www.datacamp.com/profile/anggoletomiputra" alt="Datacamp">
  </div>
  
  <div class="social" style="float:left; cursor:pointer; background-color:#3C565B;" onclick="window.open('https://www.hackerrank.com/anggoletomi', '_blank').focus();">
    <img src="https://img.shields.io/badge/-Hackerrank-3C565B?style=for-the-badge&logo=hackerrank&logoColor=white&link=https://www.hackerrank.com/anggoletomi" alt="Hackerrank">
  </div>
  
  <div style="clear:both"></div>

  <span style="color:green; font-weight:700; font-size:20px; font-style: italic">
    Click on one of the pages above to see more details.
  </span>
  
theme: jekyll-theme-minimal
# remote_theme: "godalming123/minimal"
google_analytics: G-KY0E3ESDBQ # your Google Analytics tracking ID here
